"""initial schema

Revision ID: 3d7f0256b3ad
Revises: 
Create Date: 2026-05-06 06:12:21.684937

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3d7f0256b3ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_tenant_id'), 'tenants', ['tenant_id'], unique=True)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('channel_type', sa.String(length=32), server_default='web', nullable=False),
    sa.Column('access_mode', sa.String(length=16), server_default='url', nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('favicon_url', sa.String(length=512), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_channels_tenant_id', 'channels', ['tenant_id'], unique=False)
    op.create_index('ix_channels_tenant_type', 'channels', ['tenant_id', 'channel_type'], unique=False)
    op.create_table('cs_summary_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_cs_summary_configs_tenant')
    )
    op.create_table('employee_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_employee_groups_tenant_name')
    )
    op.create_index('ix_employee_groups_tenant_id', 'employee_groups', ['tenant_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('roles', sa.JSON(), server_default='["agent"]', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=64), server_default='', nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('job_number', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('max_concurrent', sa.Integer(), server_default='10', nullable=False),
    sa.Column('default_language', sa.String(length=10), server_default='system', nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'username', name='uq_employees_tenant_username')
    )
    op.create_index('ix_employees_tenant_email', 'employees', ['tenant_id', 'email'], unique=False)
    op.create_index('ix_employees_tenant_job_number', 'employees', ['tenant_id', 'job_number'], unique=False)
    op.create_table('entity_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=32), server_default='user', nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=128), nullable=True),
    sa.Column('field_key', sa.String(length=128), nullable=False),
    sa.Column('field_label', sa.String(length=128), nullable=False),
    sa.Column('field_source', sa.String(length=32), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entity_changes_entity', 'entity_changes', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_entity_changes_tenant_entity_created', 'entity_changes', ['tenant_id', 'entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('fd_field_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), server_default='custom', nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('field_type', sa.String(length=32), nullable=False),
    sa.Column('type_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('slot_column', sa.String(length=16), nullable=False),
    sa.Column('applicable_modules', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('show_in_workspace', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'domain', 'name', name='uq_fd_field_defs_tenant_domain_name')
    )
    op.create_index('ix_fd_field_defs_tenant_domain', 'fd_field_definitions', ['tenant_id', 'domain'], unique=False)
    op.create_index('ix_fd_field_defs_tenant_domain_status', 'fd_field_definitions', ['tenant_id', 'domain', 'status'], unique=False)
    op.create_table('fd_form_layouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('scene', sa.String(length=32), nullable=False),
    sa.Column('columns_per_row', sa.Integer(), server_default='1', nullable=False),
    sa.Column('label_position', sa.String(length=16), server_default='top', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'scene', name='uq_fd_form_layouts_tenant_scene')
    )
    op.create_index('ix_fd_form_layouts_tenant', 'fd_form_layouts', ['tenant_id'], unique=False)
    op.create_table('fd_system_field_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('show_in_workspace', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'domain', 'field_key', name='uq_sys_override_tenant_domain_key')
    )
    op.create_index('ix_sys_override_tenant_domain', 'fd_system_field_overrides', ['tenant_id', 'domain'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_actor_type', sa.String(length=32), nullable=True),
    sa.Column('created_by_actor_id', sa.Integer(), nullable=True),
    sa.Column('created_by_actor_name', sa.String(length=128), nullable=True),
    sa.Column('updated_by_actor_type', sa.String(length=32), nullable=True),
    sa.Column('updated_by_actor_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_actor_name', sa.String(length=128), nullable=True),
    sa.Column('str_1', sa.String(length=2048), nullable=True),
    sa.Column('str_2', sa.String(length=2048), nullable=True),
    sa.Column('str_3', sa.String(length=2048), nullable=True),
    sa.Column('str_4', sa.String(length=2048), nullable=True),
    sa.Column('str_5', sa.String(length=2048), nullable=True),
    sa.Column('str_6', sa.String(length=2048), nullable=True),
    sa.Column('str_7', sa.String(length=2048), nullable=True),
    sa.Column('str_8', sa.String(length=2048), nullable=True),
    sa.Column('str_9', sa.String(length=2048), nullable=True),
    sa.Column('str_10', sa.String(length=2048), nullable=True),
    sa.Column('str_11', sa.String(length=2048), nullable=True),
    sa.Column('str_12', sa.String(length=2048), nullable=True),
    sa.Column('str_13', sa.String(length=2048), nullable=True),
    sa.Column('str_14', sa.String(length=2048), nullable=True),
    sa.Column('str_15', sa.String(length=2048), nullable=True),
    sa.Column('str_16', sa.String(length=2048), nullable=True),
    sa.Column('str_17', sa.String(length=2048), nullable=True),
    sa.Column('str_18', sa.String(length=2048), nullable=True),
    sa.Column('str_19', sa.String(length=2048), nullable=True),
    sa.Column('str_20', sa.String(length=2048), nullable=True),
    sa.Column('text_1', sa.Text(), nullable=True),
    sa.Column('text_2', sa.Text(), nullable=True),
    sa.Column('text_3', sa.Text(), nullable=True),
    sa.Column('text_4', sa.Text(), nullable=True),
    sa.Column('text_5', sa.Text(), nullable=True),
    sa.Column('num_1', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_2', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_3', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_4', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_5', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_6', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_7', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_8', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_9', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_10', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('date_1', sa.Date(), nullable=True),
    sa.Column('date_2', sa.Date(), nullable=True),
    sa.Column('date_3', sa.Date(), nullable=True),
    sa.Column('date_4', sa.Date(), nullable=True),
    sa.Column('date_5', sa.Date(), nullable=True),
    sa.Column('datetime_1', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_2', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_3', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_4', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_5', sa.DateTime(timezone=True), nullable=True),
    sa.Column('json_1', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_2', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_3', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_4', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_5', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_6', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_7', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_8', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_9', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_10', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_organizations_tenant_id', 'organizations', ['tenant_id'], unique=False)
    op.create_table('service_hours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weekly_schedules', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('holidays', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('makeup_days', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_hours_tenant_id', 'service_hours', ['tenant_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('default_language', sa.String(length=10), server_default='zh', nullable=False),
    sa.Column('default_timezone', sa.String(length=64), server_default='Asia/Shanghai', nullable=False),
    sa.Column('organization_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_system_settings_tenant')
    )
    op.create_table('voice_flows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_voice_flows_tenant_id', 'voice_flows', ['tenant_id'], unique=False)
    op.create_table('cs_summary_config_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=True),
    sa.Column('field_key', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['cs_summary_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_definition_id'], ['fd_field_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'field_definition_id', name='uq_cs_cfg_field_def'),
    sa.UniqueConstraint('config_id', 'field_key', name='uq_cs_cfg_field_key')
    )
    op.create_index('ix_cs_summary_config_fields_config', 'cs_summary_config_fields', ['config_id'], unique=False)
    op.create_table('cs_summary_interaction_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('condition_logic', sa.String(length=8), server_default='and', nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['cs_summary_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cs_summary_interaction_rules_config', 'cs_summary_interaction_rules', ['config_id'], unique=False)
    op.create_table('employee_group_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['employee_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'employee_id', name='uq_group_members_group_employee')
    )
    op.create_index('ix_group_members_employee_id', 'employee_group_members', ['employee_id'], unique=False)
    op.create_index('ix_group_members_group_id', 'employee_group_members', ['group_id'], unique=False)
    op.create_table('fd_field_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_definition_id'], ['fd_field_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_definition_id', 'value', name='uq_fd_field_options_field_value')
    )
    op.create_index('ix_fd_field_options_field_id', 'fd_field_options', ['field_definition_id'], unique=False)
    op.create_table('fd_form_layout_tabs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['layout_id'], ['fd_form_layouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fd_form_layout_tabs_layout', 'fd_form_layout_tabs', ['layout_id'], unique=False)
    op.create_table('fd_interaction_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('condition_logic', sa.String(length=8), server_default='and', nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['layout_id'], ['fd_form_layouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fd_interaction_rules_layout', 'fd_interaction_rules', ['layout_id'], unique=False)
    op.create_table('fd_tree_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_definition_id'], ['fd_field_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['fd_tree_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_definition_id', 'value', name='uq_fd_tree_nodes_field_value')
    )
    op.create_index('ix_fd_tree_nodes_field_id', 'fd_tree_nodes', ['field_definition_id'], unique=False)
    op.create_index('ix_fd_tree_nodes_parent_id', 'fd_tree_nodes', ['parent_id'], unique=False)
    op.create_table('inbound_routing_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('target_voice_flow_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_voice_flow_id'], ['voice_flows.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inbound_routing_rules_tenant_id', 'inbound_routing_rules', ['tenant_id'], unique=False)
    op.create_index('ix_inbound_routing_rules_tenant_priority', 'inbound_routing_rules', ['tenant_id', 'priority'], unique=False)
    op.create_table('organization_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('condition_logic', sa.String(length=8), server_default='and', nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('group_field_id', sa.Integer(), nullable=True),
    sa.Column('custom_columns_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('columns_config', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_field_id'], ['fd_field_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_organization_views_tenant', 'organization_views', ['tenant_id'], unique=False)
    op.create_index('ix_organization_views_tenant_sort', 'organization_views', ['tenant_id', 'sort_order'], unique=False)
    op.create_table('session_routing_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('target_group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_group_id'], ['employee_groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_routing_rules_tenant_id', 'session_routing_rules', ['tenant_id'], unique=False)
    op.create_index('ix_session_routing_rules_tenant_priority', 'session_routing_rules', ['tenant_id', 'priority'], unique=False)
    op.create_table('ticket_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('condition_logic', sa.String(length=8), server_default='and', nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('group_field_id', sa.Integer(), nullable=True),
    sa.Column('custom_columns_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('columns_config', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_field_id'], ['fd_field_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_views_tenant', 'ticket_views', ['tenant_id'], unique=False)
    op.create_index('ix_ticket_views_tenant_sort', 'ticket_views', ['tenant_id', 'sort_order'], unique=False)
    op.create_table('user_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('condition_logic', sa.String(length=8), server_default='and', nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('group_field_id', sa.Integer(), nullable=True),
    sa.Column('custom_columns_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('columns_config', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_field_id'], ['fd_field_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_views_tenant', 'user_views', ['tenant_id'], unique=False)
    op.create_index('ix_user_views_tenant_sort', 'user_views', ['tenant_id', 'sort_order'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('remark', sa.String(length=2000), nullable=True),
    sa.Column('web_id', sa.String(length=128), nullable=True),
    sa.Column('avatar_color', sa.String(length=16), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_actor_type', sa.String(length=32), nullable=True),
    sa.Column('created_by_actor_id', sa.Integer(), nullable=True),
    sa.Column('created_by_actor_name', sa.String(length=128), nullable=True),
    sa.Column('updated_by_actor_type', sa.String(length=32), nullable=True),
    sa.Column('updated_by_actor_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_actor_name', sa.String(length=128), nullable=True),
    sa.Column('str_1', sa.String(length=2048), nullable=True),
    sa.Column('str_2', sa.String(length=2048), nullable=True),
    sa.Column('str_3', sa.String(length=2048), nullable=True),
    sa.Column('str_4', sa.String(length=2048), nullable=True),
    sa.Column('str_5', sa.String(length=2048), nullable=True),
    sa.Column('str_6', sa.String(length=2048), nullable=True),
    sa.Column('str_7', sa.String(length=2048), nullable=True),
    sa.Column('str_8', sa.String(length=2048), nullable=True),
    sa.Column('str_9', sa.String(length=2048), nullable=True),
    sa.Column('str_10', sa.String(length=2048), nullable=True),
    sa.Column('str_11', sa.String(length=2048), nullable=True),
    sa.Column('str_12', sa.String(length=2048), nullable=True),
    sa.Column('str_13', sa.String(length=2048), nullable=True),
    sa.Column('str_14', sa.String(length=2048), nullable=True),
    sa.Column('str_15', sa.String(length=2048), nullable=True),
    sa.Column('str_16', sa.String(length=2048), nullable=True),
    sa.Column('str_17', sa.String(length=2048), nullable=True),
    sa.Column('str_18', sa.String(length=2048), nullable=True),
    sa.Column('str_19', sa.String(length=2048), nullable=True),
    sa.Column('str_20', sa.String(length=2048), nullable=True),
    sa.Column('text_1', sa.Text(), nullable=True),
    sa.Column('text_2', sa.Text(), nullable=True),
    sa.Column('text_3', sa.Text(), nullable=True),
    sa.Column('text_4', sa.Text(), nullable=True),
    sa.Column('text_5', sa.Text(), nullable=True),
    sa.Column('num_1', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_2', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_3', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_4', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_5', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_6', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_7', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_8', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_9', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_10', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('date_1', sa.Date(), nullable=True),
    sa.Column('date_2', sa.Date(), nullable=True),
    sa.Column('date_3', sa.Date(), nullable=True),
    sa.Column('date_4', sa.Date(), nullable=True),
    sa.Column('date_5', sa.Date(), nullable=True),
    sa.Column('datetime_1', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_2', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_3', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_4', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_5', sa.DateTime(timezone=True), nullable=True),
    sa.Column('json_1', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_2', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_3', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_4', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_5', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_6', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_7', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_8', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_9', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_10', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_id', name='uq_users_tenant_external')
    )
    op.create_index('ix_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='queued', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_by', sa.String(length=16), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_preview', sa.String(length=200), nullable=True),
    sa.Column('unread_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['employee_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_channel_id', 'conversations', ['channel_id'], unique=False)
    op.create_index('ix_conversations_last_message_at', 'conversations', ['last_message_at'], unique=False)
    op.create_index('ix_conversations_tenant_agent_status', 'conversations', ['tenant_id', 'agent_id', 'status'], unique=False)
    op.create_index('ix_conversations_tenant_started_at', 'conversations', ['tenant_id', 'started_at'], unique=False)
    op.create_index('ix_conversations_tenant_status', 'conversations', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_conversations_tenant_visitor', 'conversations', ['tenant_id', 'visitor_id'], unique=False)
    op.create_table('fd_form_layout_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tab_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_collapsed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tab_id'], ['fd_form_layout_tabs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fd_form_layout_sections_tab', 'fd_form_layout_sections', ['tab_id'], unique=False)
    op.create_table('cs_summary_field_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=True),
    sa.Column('field_key', sa.String(length=64), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_definition_id'], ['fd_field_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cs_summary_field_values_tenant_conversation', 'cs_summary_field_values', ['tenant_id', 'conversation_id'], unique=False)
    op.create_index('uq_cs_summary_values_field_def', 'cs_summary_field_values', ['tenant_id', 'conversation_id', 'field_definition_id'], unique=True, postgresql_where=sa.text('field_definition_id IS NOT NULL'))
    op.create_index('uq_cs_summary_values_field_key', 'cs_summary_field_values', ['tenant_id', 'conversation_id', 'field_key'], unique=True, postgresql_where=sa.text('field_key IS NOT NULL'))
    op.create_table('fd_form_layout_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=True),
    sa.Column('field_key', sa.String(length=64), nullable=True),
    sa.Column('field_source', sa.String(length=32), server_default='ticket', nullable=False),
    sa.Column('default_state', sa.String(length=16), server_default='optional', nullable=False),
    sa.Column('column_span', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_definition_id'], ['fd_field_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['fd_form_layout_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'field_definition_id', 'field_source', name='uq_fd_layout_fields_section_field_def_src'),
    sa.UniqueConstraint('section_id', 'field_key', 'field_source', name='uq_fd_layout_fields_section_field_key_src')
    )
    op.create_index('ix_fd_form_layout_fields_section', 'fd_form_layout_fields', ['section_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.String(length=16), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=16), server_default='text', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_messages_tenant_conversation', 'messages', ['tenant_id', 'conversation_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=64), nullable=True),
    sa.Column('layout_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('assignee_group_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='open', nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_actor_type', sa.String(length=32), nullable=True),
    sa.Column('created_by_actor_id', sa.Integer(), nullable=True),
    sa.Column('created_by_actor_name', sa.String(length=128), nullable=True),
    sa.Column('updated_by_actor_type', sa.String(length=32), nullable=True),
    sa.Column('updated_by_actor_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_actor_name', sa.String(length=128), nullable=True),
    sa.Column('str_1', sa.String(length=2048), nullable=True),
    sa.Column('str_2', sa.String(length=2048), nullable=True),
    sa.Column('str_3', sa.String(length=2048), nullable=True),
    sa.Column('str_4', sa.String(length=2048), nullable=True),
    sa.Column('str_5', sa.String(length=2048), nullable=True),
    sa.Column('str_6', sa.String(length=2048), nullable=True),
    sa.Column('str_7', sa.String(length=2048), nullable=True),
    sa.Column('str_8', sa.String(length=2048), nullable=True),
    sa.Column('str_9', sa.String(length=2048), nullable=True),
    sa.Column('str_10', sa.String(length=2048), nullable=True),
    sa.Column('str_11', sa.String(length=2048), nullable=True),
    sa.Column('str_12', sa.String(length=2048), nullable=True),
    sa.Column('str_13', sa.String(length=2048), nullable=True),
    sa.Column('str_14', sa.String(length=2048), nullable=True),
    sa.Column('str_15', sa.String(length=2048), nullable=True),
    sa.Column('str_16', sa.String(length=2048), nullable=True),
    sa.Column('str_17', sa.String(length=2048), nullable=True),
    sa.Column('str_18', sa.String(length=2048), nullable=True),
    sa.Column('str_19', sa.String(length=2048), nullable=True),
    sa.Column('str_20', sa.String(length=2048), nullable=True),
    sa.Column('text_1', sa.Text(), nullable=True),
    sa.Column('text_2', sa.Text(), nullable=True),
    sa.Column('text_3', sa.Text(), nullable=True),
    sa.Column('text_4', sa.Text(), nullable=True),
    sa.Column('text_5', sa.Text(), nullable=True),
    sa.Column('num_1', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_2', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_3', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_4', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_5', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_6', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_7', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_8', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_9', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('num_10', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('date_1', sa.Date(), nullable=True),
    sa.Column('date_2', sa.Date(), nullable=True),
    sa.Column('date_3', sa.Date(), nullable=True),
    sa.Column('date_4', sa.Date(), nullable=True),
    sa.Column('date_5', sa.Date(), nullable=True),
    sa.Column('datetime_1', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_2', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_3', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_4', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_5', sa.DateTime(timezone=True), nullable=True),
    sa.Column('json_1', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_2', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_3', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_4', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_5', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_6', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_7', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_8', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_9', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_10', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assignee_group_id'], ['employee_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['layout_id'], ['fd_form_layouts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_number')
    )
    op.create_index('ix_tickets_agent', 'tickets', ['agent_id'], unique=False)
    op.create_index('ix_tickets_assignee_group', 'tickets', ['assignee_group_id'], unique=False)
    op.create_index('ix_tickets_conversation', 'tickets', ['conversation_id'], unique=False)
    op.create_index('ix_tickets_tenant', 'tickets', ['tenant_id'], unique=False)
    op.create_index('ix_tickets_tenant_status', 'tickets', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_tickets_user', 'tickets', ['user_id'], unique=False)
    op.create_table('ticket_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=32), server_default='user', nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=128), nullable=True),
    sa.Column('field_key', sa.String(length=128), nullable=False),
    sa.Column('field_label', sa.String(length=128), nullable=False),
    sa.Column('field_source', sa.String(length=32), server_default='ticket', nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_changes_tenant_ticket_created', 'ticket_changes', ['tenant_id', 'ticket_id', 'created_at'], unique=False)
    op.create_index('ix_ticket_changes_ticket', 'ticket_changes', ['ticket_id'], unique=False)
    op.create_table('ticket_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=128), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_format', sa.String(length=16), server_default='html', nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_comments_tenant_ticket_created', 'ticket_comments', ['tenant_id', 'ticket_id', 'created_at'], unique=False)
    op.create_index('ix_ticket_comments_ticket', 'ticket_comments', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_comments_ticket', table_name='ticket_comments')
    op.drop_index('ix_ticket_comments_tenant_ticket_created', table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.drop_index('ix_ticket_changes_ticket', table_name='ticket_changes')
    op.drop_index('ix_ticket_changes_tenant_ticket_created', table_name='ticket_changes')
    op.drop_table('ticket_changes')
    op.drop_index('ix_tickets_user', table_name='tickets')
    op.drop_index('ix_tickets_tenant_status', table_name='tickets')
    op.drop_index('ix_tickets_tenant', table_name='tickets')
    op.drop_index('ix_tickets_conversation', table_name='tickets')
    op.drop_index('ix_tickets_assignee_group', table_name='tickets')
    op.drop_index('ix_tickets_agent', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_messages_tenant_conversation', table_name='messages')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_fd_form_layout_fields_section', table_name='fd_form_layout_fields')
    op.drop_table('fd_form_layout_fields')
    op.drop_index('uq_cs_summary_values_field_key', table_name='cs_summary_field_values', postgresql_where=sa.text('field_key IS NOT NULL'))
    op.drop_index('uq_cs_summary_values_field_def', table_name='cs_summary_field_values', postgresql_where=sa.text('field_definition_id IS NOT NULL'))
    op.drop_index('ix_cs_summary_field_values_tenant_conversation', table_name='cs_summary_field_values')
    op.drop_table('cs_summary_field_values')
    op.drop_index('ix_fd_form_layout_sections_tab', table_name='fd_form_layout_sections')
    op.drop_table('fd_form_layout_sections')
    op.drop_index('ix_conversations_tenant_visitor', table_name='conversations')
    op.drop_index('ix_conversations_tenant_status', table_name='conversations')
    op.drop_index('ix_conversations_tenant_started_at', table_name='conversations')
    op.drop_index('ix_conversations_tenant_agent_status', table_name='conversations')
    op.drop_index('ix_conversations_last_message_at', table_name='conversations')
    op.drop_index('ix_conversations_channel_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_users_tenant_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_user_views_tenant_sort', table_name='user_views')
    op.drop_index('ix_user_views_tenant', table_name='user_views')
    op.drop_table('user_views')
    op.drop_index('ix_ticket_views_tenant_sort', table_name='ticket_views')
    op.drop_index('ix_ticket_views_tenant', table_name='ticket_views')
    op.drop_table('ticket_views')
    op.drop_index('ix_session_routing_rules_tenant_priority', table_name='session_routing_rules')
    op.drop_index('ix_session_routing_rules_tenant_id', table_name='session_routing_rules')
    op.drop_table('session_routing_rules')
    op.drop_index('ix_organization_views_tenant_sort', table_name='organization_views')
    op.drop_index('ix_organization_views_tenant', table_name='organization_views')
    op.drop_table('organization_views')
    op.drop_index('ix_inbound_routing_rules_tenant_priority', table_name='inbound_routing_rules')
    op.drop_index('ix_inbound_routing_rules_tenant_id', table_name='inbound_routing_rules')
    op.drop_table('inbound_routing_rules')
    op.drop_index('ix_fd_tree_nodes_parent_id', table_name='fd_tree_nodes')
    op.drop_index('ix_fd_tree_nodes_field_id', table_name='fd_tree_nodes')
    op.drop_table('fd_tree_nodes')
    op.drop_index('ix_fd_interaction_rules_layout', table_name='fd_interaction_rules')
    op.drop_table('fd_interaction_rules')
    op.drop_index('ix_fd_form_layout_tabs_layout', table_name='fd_form_layout_tabs')
    op.drop_table('fd_form_layout_tabs')
    op.drop_index('ix_fd_field_options_field_id', table_name='fd_field_options')
    op.drop_table('fd_field_options')
    op.drop_index('ix_group_members_group_id', table_name='employee_group_members')
    op.drop_index('ix_group_members_employee_id', table_name='employee_group_members')
    op.drop_table('employee_group_members')
    op.drop_index('ix_cs_summary_interaction_rules_config', table_name='cs_summary_interaction_rules')
    op.drop_table('cs_summary_interaction_rules')
    op.drop_index('ix_cs_summary_config_fields_config', table_name='cs_summary_config_fields')
    op.drop_table('cs_summary_config_fields')
    op.drop_index('ix_voice_flows_tenant_id', table_name='voice_flows')
    op.drop_table('voice_flows')
    op.drop_table('system_settings')
    op.drop_index('ix_service_hours_tenant_id', table_name='service_hours')
    op.drop_table('service_hours')
    op.drop_index('ix_organizations_tenant_id', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_sys_override_tenant_domain', table_name='fd_system_field_overrides')
    op.drop_table('fd_system_field_overrides')
    op.drop_index('ix_fd_form_layouts_tenant', table_name='fd_form_layouts')
    op.drop_table('fd_form_layouts')
    op.drop_index('ix_fd_field_defs_tenant_domain_status', table_name='fd_field_definitions')
    op.drop_index('ix_fd_field_defs_tenant_domain', table_name='fd_field_definitions')
    op.drop_table('fd_field_definitions')
    op.drop_index('ix_entity_changes_tenant_entity_created', table_name='entity_changes')
    op.drop_index('ix_entity_changes_entity', table_name='entity_changes')
    op.drop_table('entity_changes')
    op.drop_index('ix_employees_tenant_job_number', table_name='employees')
    op.drop_index('ix_employees_tenant_email', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_employee_groups_tenant_id', table_name='employee_groups')
    op.drop_table('employee_groups')
    op.drop_table('cs_summary_configs')
    op.drop_index('ix_channels_tenant_type', table_name='channels')
    op.drop_index('ix_channels_tenant_id', table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_tenants_tenant_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
